**Please provide a similar table for your favorite 7 cities of Turkey that include their area and population.**

In [4]:
####################################
#      DATA SCIENCE BOOTCAMP       #
# File name : TASK-3A.ipynb        #
# Author    : Çağatay KARASU       #
####################################

import pandas as pd

population_dict = {'Balıkesir': 1250610,
                   'Antalya': 2619832,
                   'Eskişehir': 898369,
                   'Bursa': 3147818,
                   'Çanakkale': 557276,
                   'İzmir':4425789,
                   'Kocaeli':2033441}

area_dict = {'Balıkesir': 14583,
             'Antalya': 20177,
             'Eskişehir': 13960,
             'Bursa': 10813,
             'Çanakkale': 9817,
             'İzmir':11891,
             'Kocaeli':3397}

cities = pd.DataFrame({'population': pd.Series(population_dict),
                       'area': pd.Series(area_dict)})
cities

           population   area
Balıkesir     1250610  14583
Antalya       2619832  20177
Eskişehir      898369  13960
Bursa         3147818  10813
Çanakkale      557276   9817
İzmir         4425789  11891
Kocaeli       2033441   3397